version: "{build}"

image: Visual Studio 2022

clone_folder: c:\gopath\src\gobot.io\x\gobot

environment:
  PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  GOPATH: c:\gopath

before_test:
  - go version
  - go env

build_script:
  - go test -race -v .
  - go test -race -v ./pkg/drivers/aio/...
  - go test -race -v ./pkg/drivers/ble/...
  - go test -race -v ./pkg/drivers/serial/...
  - go test -race -v ./pkg/platforms/bleclient/...
  - go test -race -v ./pkg/platforms/dji/...
  - go test -race -v ./pkg/platforms/firmata/...
  - go test -race -v ./pkg/platforms/joystick/...
  - go test -race -v ./pkg/platforms/parrot/...
  - go test -race -v ./pkg/platforms/serialport/...
